<a href="https://colab.research.google.com/github/sudip234-source/PyTorch-Tutorial/blob/main/Introduction_to_Tensor_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.device_count())
# print(torch.cuda.current_device())
# print(torch.cuda.get_device_name(0))

2.6.0+cu124
False
0


In [2]:
a = torch.empty(2,3)

tensor([[2.6199e+36, 4.5321e-41, 2.6200e+36],
        [4.5321e-41, 2.6200e+36, 4.5321e-41]])

In [4]:
a = torch.empty(2,3)
# print(a)
type(a)

torch.Tensor

In [5]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.zeros(4,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [8]:
torch.rand(2,3)

tensor([[0.0125, 0.7987, 0.4393],
        [0.3774, 0.5691, 0.4950]])

In [9]:
# Reproducibility
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.arange(0,10,3)

tensor([0, 3, 6, 9])

In [18]:
(torch.linspace(3,5,10))

tensor([3.0000, 3.2222, 3.4444, 3.6667, 3.8889, 4.1111, 4.3333, 4.5556, 4.7778,
        5.0000])

In [19]:
torch.eye(6)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [21]:
torch.full((2,3),7)

tensor([[7, 7, 7],
        [7, 7, 7]])

In [22]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [24]:
torch.empty_like(x)

tensor([[    138914237242672,     138914237242672, 2318265739929350004],
        [2322206376936961058, 8606218820622040098, 7598454517878898286]])

In [25]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [26]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [27]:
x.dtype

torch.int64

In [28]:
torch.tensor([1.5,2.,3.6],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [30]:
torch.tensor([1,2.,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [31]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [32]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [33]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [36]:
torch.neg(torch.tensor([1,2,-4,5]))

tensor([-1, -2,  4, -5])

In [39]:
torch.clamp(torch.tensor([1,3,4,5]),min=-2,max=2)

tensor([1, 2, 2, 2])

In [42]:
e = torch.randint(size=(2,3),low=10,high=20)
print(e)
print(torch.argmax(e))
torch.sum(e)

tensor([[14, 13, 18],
        [17, 14, 16]])
tensor(2)


tensor(92)

In [43]:
torch.sum(e,dim=0), torch.sum(e,dim=1)

(tensor([31, 27, 34]), tensor([45, 47]))

In [45]:
torch.mean(e,dtype=torch.float32)

tensor(15.3333)

In [47]:
torch.mean(e,dtype=torch.float32,dim=0), torch.mean(e,dtype=torch.float64,dim=1)

(tensor([15.5000, 13.5000, 17.0000]),
 tensor([15.0000, 15.6667], dtype=torch.float64))

In [50]:
torch.median(e)

tensor(14)

In [51]:
torch.max(e), torch.min(e)

(tensor(18), tensor(13))

In [52]:
torch.prod(e)

tensor(12475008)

In [65]:
torch.std(e.float(),dim=0)

tensor([2.1213, 0.7071, 1.4142])

In [64]:
torch.var(e.float(),dim=1)

tensor([7.0000, 2.3333])

In [66]:
print(x),print(e)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[14, 13, 18],
        [17, 14, 16]])


(None, None)

In [69]:
torch.matmul(x,e.T)

tensor([[ 94,  93],
        [229, 234]])

In [70]:
torch.det(torch.rand(3,3)) # Determinant

tensor(-0.0134)

In [71]:
torch.log(e.float())

tensor([[2.6391, 2.5649, 2.8904],
        [2.8332, 2.6391, 2.7726]])

In [72]:
torch.sigmoid(e.float())

tensor([[1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]])

In [73]:
torch.exp(e.float())

tensor([[ 1202604.2500,   442413.4062, 65659968.0000],
        [24154952.0000,  1202604.2500,  8886111.0000]])

In [74]:
torch.softmax(e.float(),dim=0)

tensor([[0.0474, 0.2689, 0.8808],
        [0.9526, 0.7311, 0.1192]])

In [75]:
torch.relu(e.float())

tensor([[14., 13., 18.],
        [17., 14., 16.]])

In [76]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a),print(b)

tensor([[0.4235, 0.0169, 0.2209],
        [0.9535, 0.7064, 0.1629]])
tensor([[0.8902, 0.5163, 0.0359],
        [0.6476, 0.3430, 0.3182]])


(None, None)

inplace is denoted by __

In [77]:
a.add_(b)
a

tensor([[1.3137, 0.5332, 0.2568],
        [1.6012, 1.0494, 0.4811]])

Copying A tensor

In [78]:
y = torch.tensor([[1,2,3],[4,5,6]])
z = y
id(y),id(z) # so this is not a actual clone bec changes in y affects on z also

(138909900487472, 138909900487472)

cloning

In [79]:
r = y.clone()
id(y),id(r)

(138909900487472, 138909901069904)

In [80]:
p = torch.rand(2,3)
p

tensor([[0.5261, 0.0447, 0.5123],
        [0.9051, 0.5989, 0.4450]])

In [85]:
p.reshape(1,3,2,1)

tensor([[[[0.5261],
          [0.0447]],

         [[0.5123],
          [0.9051]],

         [[0.5989],
          [0.4450]]]])

In [86]:
p.flatten()

tensor([0.5261, 0.0447, 0.5123, 0.9051, 0.5989, 0.4450])

In [88]:
t = torch.rand(226,226,3)
t.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [96]:
t.unsqueeze(0).squeeze(0).shape

torch.Size([226, 226, 3])

## Numpy and PyTorch

In [97]:
import numpy as np

In [98]:
w = torch.tensor([1,2,3])
w.numpy()

array([1, 2, 3])

In [99]:
v = np.array([4,5,6])
torch.from_numpy(v)

tensor([4, 5, 6])