<a href="https://colab.research.google.com/github/sudip234-source/PyTorch-Tutorial/blob/main/nn_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(num_features,3)
        self.relu = nn.ReLU()

        self.linear2 = nn.Linear(3,2)
        self.relu2 = nn.ReLU()

        self.linear3 = nn.Linear(2,1)

        self.sigmoid = nn.Sigmoid()

    def forward(self,features):
        z1 = self.linear(features)
        a1 = self.relu(z1)

        z2 = self.linear2(a1)
        a2 = self.relu2(z2)

        z3 = self.linear3(a2)
        out = self.sigmoid(z3)
        return out

In [10]:
feature = torch.rand((10,5))

model = Model(feature.shape[1])
output = model(feature)

In [11]:
output

tensor([[0.3689],
        [0.3628],
        [0.3624],
        [0.3619],
        [0.3661],
        [0.3704],
        [0.3548],
        [0.3723],
        [0.3586],
        [0.3784]], grad_fn=<SigmoidBackward0>)

In [12]:
model.linear.bias

Parameter containing:
tensor([ 0.3084,  0.1229, -0.2745], requires_grad=True)

In [13]:
model.linear.weight

Parameter containing:
tensor([[ 0.4057, -0.1541,  0.1195,  0.1131,  0.1454],
        [-0.1784,  0.4388,  0.0652, -0.1132,  0.2996],
        [ 0.0715, -0.3534,  0.4300, -0.2191,  0.3289]], requires_grad=True)

In [7]:
!pip install torchinfo

In [14]:
from torchinfo import summary
summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            8
├─ReLU: 1-4                              --
├─Linear: 1-5                            3
├─Sigmoid: 1-6                           --
Total params: 29
Trainable params: 29
Non-trainable params: 0

By using Module

In [16]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 2),
        nn.ReLU(),
        nn.Linear(2, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [17]:
features = torch.rand((10,5))

model = Model(features.shape[1])
output = model(features)
output

tensor([[0.5625],
        [0.5625],
        [0.5625],
        [0.5473],
        [0.5625],
        [0.5578],
        [0.5493],
        [0.5390],
        [0.5625],
        [0.5519]], grad_fn=<SigmoidBackward0>)

In [19]:
model.named_parameters()

<generator object Module.named_parameters at 0x7d39b6150b40>

In [20]:
for name, param in model.named_parameters():
    if param.requires_grad:
        print(f"{name} → shape: {param.shape}")
        print(param)

network.0.weight → shape: torch.Size([3, 5])
Parameter containing:
tensor([[-0.0479, -0.3993, -0.1971,  0.2397, -0.0108],
        [ 0.3389, -0.0711,  0.3809, -0.0804,  0.3547],
        [-0.1535, -0.1979,  0.0564, -0.2382, -0.0910]], requires_grad=True)
network.0.bias → shape: torch.Size([3])
Parameter containing:
tensor([-0.2747, -0.3968, -0.1230], requires_grad=True)
network.2.weight → shape: torch.Size([2, 3])
Parameter containing:
tensor([[-0.3287,  0.5453, -0.5460],
        [ 0.2916,  0.5412,  0.2407]], requires_grad=True)
network.2.bias → shape: torch.Size([2])
Parameter containing:
tensor([-0.3469,  0.0806], requires_grad=True)
network.4.weight → shape: torch.Size([1, 2])
Parameter containing:
tensor([[-0.4844, -0.6743]], requires_grad=True)
network.4.bias → shape: torch.Size([1])
Parameter containing:
tensor([0.3056], requires_grad=True)


In [21]:
summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Sequential: 1-1                        --
│    └─Linear: 2-1                       18
│    └─ReLU: 2-2                         --
│    └─Linear: 2-3                       8
│    └─ReLU: 2-4                         --
│    └─Linear: 2-5                       3
│    └─Sigmoid: 2-6                      --
Total params: 29
Trainable params: 29
Non-trainable params: 0