<a href="https://colab.research.google.com/github/sudip234-source/PyTorch-Tutorial/blob/main/pytorch_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [8]:
x = torch.tensor(3.0,requires_grad=True)
x

tensor(3., requires_grad=True)

In [9]:
y = x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [12]:
# import math
z = torch.sin(y)

In [13]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [14]:
z.backward()

In [15]:
x.grad

tensor(-5.4668)

In [17]:
y.grad

<ipython-input-17-10b3a7061f6d>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  y.grad


In [18]:
# Inputs
x = torch.tensor(6.7)  # Input feature
y = torch.tensor(0.0)  # True label (binary)

w = torch.tensor(1.0)  # Weight
b = torch.tensor(0.0)  # Bias

In [19]:
# Binary Cross-Entropy Loss for scalar
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8  # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

In [20]:
# Forward pass
z = w * x + b  # Weighted sum (linear part)
y_pred = torch.sigmoid(z)  # Predicted probability

# Compute binary cross-entropy loss
loss = binary_cross_entropy_loss(y_pred, y)

In [21]:
loss

tensor(6.7012)

In [22]:
# Derivatives:
# 1. dL/d(y_pred): Loss with respect to the prediction (y_pred)
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))

# 2. dy_pred/dz: Prediction (y_pred) with respect to z (sigmoid derivative)
dy_pred_dz = y_pred * (1 - y_pred)

# 3. dz/dw and dz/db: z with respect to w and b
dz_dw = x  # dz/dw = x
dz_db = 1  # dz/db = 1 (bias contributes directly to z)

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [23]:
print(f"Manual Gradient of loss w.r.t weight (dw): {dL_dw}")
print(f"Manual Gradient of loss w.r.t bias (db): {dL_db}")

Manual Gradient of loss w.r.t weight (dw): 6.691762447357178
Manual Gradient of loss w.r.t bias (db): 0.998770534992218


In [24]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [25]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [26]:
w,b

(tensor(1., requires_grad=True), tensor(0., requires_grad=True))

In [27]:
z = w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [28]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [29]:
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [30]:
loss.backward()
w.grad,b.grad

(tensor(6.6918), tensor(0.9988))

In [32]:
x = torch.tensor([1,2,3],dtype=torch.float32,requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [33]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [34]:
y.backward()
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [36]:
x.grad.zero_()

tensor([0., 0., 0.])

Gradient Tracking Disable

In [40]:
x = torch.rand(1,requires_grad=True)
x

tensor([0.1713], requires_grad=True)

In [41]:
x

tensor([0.1713], requires_grad=True)

In [42]:
y = x**2
y

tensor([0.0293], grad_fn=<PowBackward0>)

In [43]:
y.backward()
x.grad

tensor([0.3425])

In [44]:
# 1. requires_grad_(False)
x.requires_grad_(False)

tensor([0.1713])

In [45]:
y = x**2
y

tensor([0.0293])

In [46]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [58]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [59]:
# 2.detach()
z = x.detach()
z

tensor(2.)

In [60]:
y = x ** 2

In [61]:
y

tensor(4., grad_fn=<PowBackward0>)

In [62]:
y1 = z**2
y1

tensor(4.)

In [63]:
y.backward()
x.grad

tensor(4.)

In [64]:
y1.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn